//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSDW.Presentation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LSDW.Presentation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings relevant to the dealers..
        /// </summary>
        internal static string SettingsMenu_Dealer_Description {
            get {
                return ResourceManager.GetString("SettingsMenu.Dealer.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many days it will take for the dealer to return after he has fled or been killed..
        /// </summary>
        internal static string SettingsMenu_Dealer_DownTimeInHours_Description {
            get {
                return ResourceManager.GetString("SettingsMenu.Dealer.DownTimeInHours.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down time in hours.
        /// </summary>
        internal static string SettingsMenu_Dealer_DownTimeInHours_Title {
            get {
                return ResourceManager.GetString("SettingsMenu.Dealer.DownTimeInHours.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should the dealer wear armor?.
        /// </summary>
        internal static string SettingsMenu_Dealer_HasArmor_Description {
            get {
                return ResourceManager.GetString("SettingsMenu.Dealer.HasArmor.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is wearing armor?.
        /// </summary>
        internal static string SettingsMenu_Dealer_HasArmor_Title {
            get {
                return ResourceManager.GetString("SettingsMenu.Dealer.HasArmor.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should the dealer carry one or more weapons?.
        /// </summary>
        internal static string SettingsMenu_Dealer_HasWeapons_Description {
            get {
                return ResourceManager.GetString("SettingsMenu.Dealer.HasWeapons.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is armed?.
        /// </summary>
        internal static string SettingsMenu_Dealer_HasWeapons_Title {
            get {
                return ResourceManager.GetString("SettingsMenu.Dealer.HasWeapons.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The highest armor level of the dealer..
        /// </summary>
        internal static string SettingsMenu_Dealer_MaxArmor_Description {
            get {
                return ResourceManager.GetString("SettingsMenu.Dealer.MaxArmor.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum armor.
        /// </summary>
        internal static string SettingsMenu_Dealer_MaxArmor_Title {
            get {
                return ResourceManager.GetString("SettingsMenu.Dealer.MaxArmor.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dealer&apos;s highest life point level..
        /// </summary>
        internal static string SettingsMenu_Dealer_MaxHealth_Description {
            get {
                return ResourceManager.GetString("SettingsMenu.Dealer.MaxHealth.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum health.
        /// </summary>
        internal static string SettingsMenu_Dealer_MaxHealth_Title {
            get {
                return ResourceManager.GetString("SettingsMenu.Dealer.MaxHealth.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer settings.
        /// </summary>
        internal static string SettingsMenu_Dealer_SubTitle {
            get {
                return ResourceManager.GetString("SettingsMenu.Dealer.SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings how the market behaves..
        /// </summary>
        internal static string SettingsMenu_Market_Description {
            get {
                return ResourceManager.GetString("SettingsMenu.Market.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum value of a drug, serves as a multiplier to the nominal market value..
        /// </summary>
        internal static string SettingsMenu_Market_MaximumDrugPrice_Description {
            get {
                return ResourceManager.GetString("SettingsMenu.Market.MaximumDrugPrice.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum drug value.
        /// </summary>
        internal static string SettingsMenu_Market_MaximumDrugPrice_Title {
            get {
                return ResourceManager.GetString("SettingsMenu.Market.MaximumDrugPrice.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum value of a drug, serves as a multiplier to the nominal market value..
        /// </summary>
        internal static string SettingsMenu_Market_MinimumDrugPrice_Description {
            get {
                return ResourceManager.GetString("SettingsMenu.Market.MinimumDrugPrice.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum drug value.
        /// </summary>
        internal static string SettingsMenu_Market_MinimumDrugPrice_Title {
            get {
                return ResourceManager.GetString("SettingsMenu.Market.MinimumDrugPrice.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value indicates after how many hours the drug prices change..
        /// </summary>
        internal static string SettingsMenu_Market_RefreshInterval_Description {
            get {
                return ResourceManager.GetString("SettingsMenu.Market.RefreshInterval.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price refresh interval.
        /// </summary>
        internal static string SettingsMenu_Market_RefreshInterval_Title {
            get {
                return ResourceManager.GetString("SettingsMenu.Market.RefreshInterval.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value indicates after how many hours the drug offers change..
        /// </summary>
        internal static string SettingsMenu_Market_RestockInterval_Description {
            get {
                return ResourceManager.GetString("SettingsMenu.Market.RestockInterval.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug refresh interval.
        /// </summary>
        internal static string SettingsMenu_Market_RestockInterval_Title {
            get {
                return ResourceManager.GetString("SettingsMenu.Market.RestockInterval.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How likely is it that a dealer will have a special offer..
        /// </summary>
        internal static string SettingsMenu_Market_SpecialOfferChance_Description {
            get {
                return ResourceManager.GetString("SettingsMenu.Market.SpecialOfferChance.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special offer chance.
        /// </summary>
        internal static string SettingsMenu_Market_SpecialOfferChance_Title {
            get {
                return ResourceManager.GetString("SettingsMenu.Market.SpecialOfferChance.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market settings.
        /// </summary>
        internal static string SettingsMenu_Market_SubTitle {
            get {
                return ResourceManager.GetString("SettingsMenu.Market.SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value indicates how many more drugs the player can carry per level..
        /// </summary>
        internal static string SettingsMenu_Player_BagSizePerLevel_Description {
            get {
                return ResourceManager.GetString("SettingsMenu.Player.BagSizePerLevel.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bag size per level.
        /// </summary>
        internal static string SettingsMenu_Player_BagSizePerLevel_Title {
            get {
                return ResourceManager.GetString("SettingsMenu.Player.BagSizePerLevel.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings relevant to the player..
        /// </summary>
        internal static string SettingsMenu_Player_Description {
            get {
                return ResourceManager.GetString("SettingsMenu.Player.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The experience value multiplier, which is to be applied at each experience gain..
        /// </summary>
        internal static string SettingsMenu_Player_ExperienceMultiplier_Description {
            get {
                return ResourceManager.GetString("SettingsMenu.Player.ExperienceMultiplier.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience multiplier.
        /// </summary>
        internal static string SettingsMenu_Player_ExperienceMultiplier_Title {
            get {
                return ResourceManager.GetString("SettingsMenu.Player.ExperienceMultiplier.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does the player looses the drugs he is currently carrying when he gets wasted?.
        /// </summary>
        internal static string SettingsMenu_Player_LooseDrugsOnDeath_Description {
            get {
                return ResourceManager.GetString("SettingsMenu.Player.LooseDrugsOnDeath.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loose drugs on death?.
        /// </summary>
        internal static string SettingsMenu_Player_LooseDrugsOnDeath_Title {
            get {
                return ResourceManager.GetString("SettingsMenu.Player.LooseDrugsOnDeath.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does the player looses the drugs he is currently carrying when he gets busted?.
        /// </summary>
        internal static string SettingsMenu_Player_LooseDrugsWhenBusted_Description {
            get {
                return ResourceManager.GetString("SettingsMenu.Player.LooseDrugsWhenBusted.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loose drugs when busted?.
        /// </summary>
        internal static string SettingsMenu_Player_LooseDrugsWhenBusted_Title {
            get {
                return ResourceManager.GetString("SettingsMenu.Player.LooseDrugsWhenBusted.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player settings.
        /// </summary>
        internal static string SettingsMenu_Player_SubTitle {
            get {
                return ResourceManager.GetString("SettingsMenu.Player.SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves the selected settings..
        /// </summary>
        internal static string SettingsMenu_Save_Description {
            get {
                return ResourceManager.GetString("SettingsMenu.Save.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SettingsMenu_Save_Title {
            get {
                return ResourceManager.GetString("SettingsMenu.Save.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSDW settings can be made here..
        /// </summary>
        internal static string SettingsMenu_SubTitle {
            get {
                return ResourceManager.GetString("SettingsMenu.SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsMenu_Title {
            get {
                return ResourceManager.GetString("SettingsMenu.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How likely is a DEA raid after the deal is done?.
        /// </summary>
        internal static string SettingsMenu_Trafficking_BustChance_Description {
            get {
                return ResourceManager.GetString("SettingsMenu.Trafficking.BustChance.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bust chance.
        /// </summary>
        internal static string SettingsMenu_Trafficking_BustChance_Title {
            get {
                return ResourceManager.GetString("SettingsMenu.Trafficking.BustChance.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings relevant to the trafficking mission..
        /// </summary>
        internal static string SettingsMenu_Trafficking_Description {
            get {
                return ResourceManager.GetString("SettingsMenu.Trafficking.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do the dealers have to be found first or do they appear immediately on the map?.
        /// </summary>
        internal static string SettingsMenu_Trafficking_DiscoverDealer_Description {
            get {
                return ResourceManager.GetString("SettingsMenu.Trafficking.DiscoverDealer.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to discover dealer?.
        /// </summary>
        internal static string SettingsMenu_Trafficking_DiscoverDealer_Title {
            get {
                return ResourceManager.GetString("SettingsMenu.Trafficking.DiscoverDealer.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trafficking settings.
        /// </summary>
        internal static string SettingsMenu_Trafficking_SubTitle {
            get {
                return ResourceManager.GetString("SettingsMenu.Trafficking.SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the mugshot level for a DEA raid?.
        /// </summary>
        internal static string SettingsMenu_Trafficking_WantedLevel_Description {
            get {
                return ResourceManager.GetString("SettingsMenu.Trafficking.WantedLevel.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wanted level.
        /// </summary>
        internal static string SettingsMenu_Trafficking_WantedLevel_Title {
            get {
                return ResourceManager.GetString("SettingsMenu.Trafficking.WantedLevel.Title", resourceCulture);
            }
        }
    }
}
