//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace LSDW.Infrastructure.Services;

internal sealed partial class SettingsService
{
	private void RegisterEvents()
	{
		_settings.Dealer.DownTimeInHours.Changed += (s, e) => _scriptSettings.SetValue("DEALER", "DOWNTIMEINHOURS", e.Value);
		_settings.Dealer.HasArmor.Changed += (s, e) => _scriptSettings.SetValue("DEALER", "HASARMOR", e.Value);
		_settings.Dealer.HasWeapons.Changed += (s, e) => _scriptSettings.SetValue("DEALER", "HASWEAPONS", e.Value);
		_settings.Market.MaximumDrugPrice.Changed += (s, e) => _scriptSettings.SetValue("MARKET", "MAXIMUMDRUGPRICE", e.Value);
		_settings.Market.MinimumDrugPrice.Changed += (s, e) => _scriptSettings.SetValue("MARKET", "MINIMUMDRUGPRICE", e.Value);
		_settings.Market.RefreshInterval.Changed += (s, e) => _scriptSettings.SetValue("MARKET", "REFRESHINTERVAL", e.Value);
		_settings.Market.RestockInterval.Changed += (s, e) => _scriptSettings.SetValue("MARKET", "RESTOCKINTERVAL", e.Value);
		_settings.Market.SpecialOfferChance.Changed += (s, e) => _scriptSettings.SetValue("MARKET", "SPECIALOFFERCHANCE", e.Value);
		_settings.Player.BagSizePerLevel.Changed += (s, e) => _scriptSettings.SetValue("PLAYER", "BAGSIZEPERLEVEL", e.Value);
		_settings.Player.ExperienceMultiplier.Changed += (s, e) => _scriptSettings.SetValue("PLAYER", "EXPERIENCEMULTIPLIER", e.Value);
		_settings.Player.LooseDrugsOnDeath.Changed += (s, e) => _scriptSettings.SetValue("PLAYER", "LOOSEDRUGSONDEATH", e.Value);
		_settings.Player.LooseDrugsWhenBusted.Changed += (s, e) => _scriptSettings.SetValue("PLAYER", "LOOSEDRUGSWHENBUSTED", e.Value);
		_settings.Trafficking.BustChance.Changed += (s, e) => _scriptSettings.SetValue("TRAFFICKING", "BUSTCHANCE", e.Value);
		_settings.Trafficking.DiscoverDealer.Changed += (s, e) => _scriptSettings.SetValue("TRAFFICKING", "DISCOVERDEALER", e.Value);
		_settings.Trafficking.WantedLevel.Changed += (s, e) => _scriptSettings.SetValue("TRAFFICKING", "WANTEDLEVEL", e.Value);
	}

	private void LoadInternal()
	{
		_settings.Dealer.DownTimeInHours.Value = _scriptSettings.GetValue(
			section: "DEALER",
			name: "DOWNTIMEINHOURS",
			defaultvalue: _settings.Dealer.DownTimeInHours.Value
			);
		_settings.Dealer.HasArmor.Value = _scriptSettings.GetValue(
			section: "DEALER",
			name: "HASARMOR",
			defaultvalue: _settings.Dealer.HasArmor.Value
			);
		_settings.Dealer.HasWeapons.Value = _scriptSettings.GetValue(
			section: "DEALER",
			name: "HASWEAPONS",
			defaultvalue: _settings.Dealer.HasWeapons.Value
			);
		_settings.Market.MaximumDrugPrice.Value = _scriptSettings.GetValue(
			section: "MARKET",
			name: "MAXIMUMDRUGPRICE",
			defaultvalue: _settings.Market.MaximumDrugPrice.Value
			);
		_settings.Market.MinimumDrugPrice.Value = _scriptSettings.GetValue(
			section: "MARKET",
			name: "MINIMUMDRUGPRICE",
			defaultvalue: _settings.Market.MinimumDrugPrice.Value
			);
		_settings.Market.RefreshInterval.Value = _scriptSettings.GetValue(
			section: "MARKET",
			name: "REFRESHINTERVAL",
			defaultvalue: _settings.Market.RefreshInterval.Value
			);
		_settings.Market.RestockInterval.Value = _scriptSettings.GetValue(
			section: "MARKET",
			name: "RESTOCKINTERVAL",
			defaultvalue: _settings.Market.RestockInterval.Value
			);
		_settings.Market.SpecialOfferChance.Value = _scriptSettings.GetValue(
			section: "MARKET",
			name: "SPECIALOFFERCHANCE",
			defaultvalue: _settings.Market.SpecialOfferChance.Value
			);
		_settings.Player.BagSizePerLevel.Value = _scriptSettings.GetValue(
			section: "PLAYER",
			name: "BAGSIZEPERLEVEL",
			defaultvalue: _settings.Player.BagSizePerLevel.Value
			);
		_settings.Player.ExperienceMultiplier.Value = _scriptSettings.GetValue(
			section: "PLAYER",
			name: "EXPERIENCEMULTIPLIER",
			defaultvalue: _settings.Player.ExperienceMultiplier.Value
			);
		_settings.Player.LooseDrugsOnDeath.Value = _scriptSettings.GetValue(
			section: "PLAYER",
			name: "LOOSEDRUGSONDEATH",
			defaultvalue: _settings.Player.LooseDrugsOnDeath.Value
			);
		_settings.Player.LooseDrugsWhenBusted.Value = _scriptSettings.GetValue(
			section: "PLAYER",
			name: "LOOSEDRUGSWHENBUSTED",
			defaultvalue: _settings.Player.LooseDrugsWhenBusted.Value
			);
		_settings.Trafficking.BustChance.Value = _scriptSettings.GetValue(
			section: "TRAFFICKING",
			name: "BUSTCHANCE",
			defaultvalue: _settings.Trafficking.BustChance.Value
			);
		_settings.Trafficking.DiscoverDealer.Value = _scriptSettings.GetValue(
			section: "TRAFFICKING",
			name: "DISCOVERDEALER",
			defaultvalue: _settings.Trafficking.DiscoverDealer.Value
			);
		_settings.Trafficking.WantedLevel.Value = _scriptSettings.GetValue(
			section: "TRAFFICKING",
			name: "WANTEDLEVEL",
			defaultvalue: _settings.Trafficking.WantedLevel.Value
			);
	}

	private void SaveInternal()
	{
		_scriptSettings.Save();
	}
}
