//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace LSDW.Infrastructure.Services;

internal sealed partial class SettingsService
{
	private void RegisterEvents()
	{
		_settings.Dealer.DownTimeInHours.Changed += (s, e) => _scriptSettings.SetValue("DEALER", "DOWNTIMEINHOURS", e.Value);
		_settings.Dealer.HasArmor.Changed += (s, e) => _scriptSettings.SetValue("DEALER", "HASARMOR", e.Value);
		_settings.Dealer.HasWeapons.Changed += (s, e) => _scriptSettings.SetValue("DEALER", "HASWEAPONS", e.Value);
		_settings.Market.RestockInterval.Changed += (s, e) => _scriptSettings.SetValue("MARKET", "RESTOCKINTERVAL", e.Value);
		_settings.Market.MaximumDrugPrice.Changed += (s, e) => _scriptSettings.SetValue("MARKET", "MAXIMUMDRUGPRICE", e.Value);
		_settings.Market.MinimumDrugPrice.Changed += (s, e) => _scriptSettings.SetValue("MARKET", "MINIMUMDRUGPRICE", e.Value);
		_settings.Market.RefreshInterval.Changed += (s, e) => _scriptSettings.SetValue("MARKET", "REFRESHINTERVAL", e.Value);
		_settings.Market.SpecialOfferChance.Changed += (s, e) => _scriptSettings.SetValue("MARKET", "SPECIALOFFERCHANCE", e.Value);
		_settings.Player.ExperienceMultiplier.Changed += (s, e) => _scriptSettings.SetValue("PLAYER", "EXPERIENCEMULTIPLIER", e.Value);
		_settings.Player.BagSizePerLevel.Changed += (s, e) => _scriptSettings.SetValue("PLAYER", "BAGSIZEPERLEVEL", e.Value);
		_settings.Player.LooseDrugsOnDeath.Changed += (s, e) => _scriptSettings.SetValue("PLAYER", "LOOSEDRUGSONDEATH", e.Value);
		_settings.Player.LooseDrugsWhenBusted.Changed += (s, e) => _scriptSettings.SetValue("PLAYER", "LOOSEDRUGSWHENBUSTED", e.Value);
		_settings.Player.LooseMoneyOnDeath.Changed += (s, e) => _scriptSettings.SetValue("PLAYER", "LOOSEMONEYONDEATH", e.Value);
		_settings.Player.LooseMoneyWhenBusted.Changed += (s, e) => _scriptSettings.SetValue("PLAYER", "LOOSEMONEYWHENBUSTED", e.Value);
		_settings.Trafficking.BustChance.Changed += (s, e) => _scriptSettings.SetValue("TRAFFICKING", "BUSTCHANCE", e.Value);
		_settings.Trafficking.DiscoverDealer.Changed += (s, e) => _scriptSettings.SetValue("TRAFFICKING", "DISCOVERDEALER", e.Value);
		_settings.Trafficking.WantedLevel.Changed += (s, e) => _scriptSettings.SetValue("TRAFFICKING", "WANTEDLEVEL", e.Value);
	}

	private void LoadInternal()
	{
		int valueDownTimeInHours = _scriptSettings.GetValue("DEALER", "DOWNTIMEINHOURS", _settings.Dealer.DownTimeInHours.Value);
		_scriptSettings.SetValue("DEALER", "DOWNTIMEINHOURS", valueDownTimeInHours);
		bool valueHasArmor = _scriptSettings.GetValue("DEALER", "HASARMOR", _settings.Dealer.HasArmor.Value);
		_scriptSettings.SetValue("DEALER", "HASARMOR", valueHasArmor);
		bool valueHasWeapons = _scriptSettings.GetValue("DEALER", "HASWEAPONS", _settings.Dealer.HasWeapons.Value);
		_scriptSettings.SetValue("DEALER", "HASWEAPONS", valueHasWeapons);
		int valueRestockInterval = _scriptSettings.GetValue("MARKET", "RESTOCKINTERVAL", _settings.Market.RestockInterval.Value);
		_scriptSettings.SetValue("MARKET", "RESTOCKINTERVAL", valueRestockInterval);
		float valueMaximumDrugPrice = _scriptSettings.GetValue("MARKET", "MAXIMUMDRUGPRICE", _settings.Market.MaximumDrugPrice.Value);
		_scriptSettings.SetValue("MARKET", "MAXIMUMDRUGPRICE", valueMaximumDrugPrice);
		float valueMinimumDrugPrice = _scriptSettings.GetValue("MARKET", "MINIMUMDRUGPRICE", _settings.Market.MinimumDrugPrice.Value);
		_scriptSettings.SetValue("MARKET", "MINIMUMDRUGPRICE", valueMinimumDrugPrice);
		int valueRefreshInterval = _scriptSettings.GetValue("MARKET", "REFRESHINTERVAL", _settings.Market.RefreshInterval.Value);
		_scriptSettings.SetValue("MARKET", "REFRESHINTERVAL", valueRefreshInterval);
		float valueSpecialOfferChance = _scriptSettings.GetValue("MARKET", "SPECIALOFFERCHANCE", _settings.Market.SpecialOfferChance.Value);
		_scriptSettings.SetValue("MARKET", "SPECIALOFFERCHANCE", valueSpecialOfferChance);
		float valueExperienceMultiplier = _scriptSettings.GetValue("PLAYER", "EXPERIENCEMULTIPLIER", _settings.Player.ExperienceMultiplier.Value);
		_scriptSettings.SetValue("PLAYER", "EXPERIENCEMULTIPLIER", valueExperienceMultiplier);
		int valueBagSizePerLevel = _scriptSettings.GetValue("PLAYER", "BAGSIZEPERLEVEL", _settings.Player.BagSizePerLevel.Value);
		_scriptSettings.SetValue("PLAYER", "BAGSIZEPERLEVEL", valueBagSizePerLevel);
		bool valueLooseDrugsOnDeath = _scriptSettings.GetValue("PLAYER", "LOOSEDRUGSONDEATH", _settings.Player.LooseDrugsOnDeath.Value);
		_scriptSettings.SetValue("PLAYER", "LOOSEDRUGSONDEATH", valueLooseDrugsOnDeath);
		bool valueLooseDrugsWhenBusted = _scriptSettings.GetValue("PLAYER", "LOOSEDRUGSWHENBUSTED", _settings.Player.LooseDrugsWhenBusted.Value);
		_scriptSettings.SetValue("PLAYER", "LOOSEDRUGSWHENBUSTED", valueLooseDrugsWhenBusted);
		bool valueLooseMoneyOnDeath = _scriptSettings.GetValue("PLAYER", "LOOSEMONEYONDEATH", _settings.Player.LooseMoneyOnDeath.Value);
		_scriptSettings.SetValue("PLAYER", "LOOSEMONEYONDEATH", valueLooseMoneyOnDeath);
		bool valueLooseMoneyWhenBusted = _scriptSettings.GetValue("PLAYER", "LOOSEMONEYWHENBUSTED", _settings.Player.LooseMoneyWhenBusted.Value);
		_scriptSettings.SetValue("PLAYER", "LOOSEMONEYWHENBUSTED", valueLooseMoneyWhenBusted);
		float valueBustChance = _scriptSettings.GetValue("TRAFFICKING", "BUSTCHANCE", _settings.Trafficking.BustChance.Value);
		_scriptSettings.SetValue("TRAFFICKING", "BUSTCHANCE", valueBustChance);
		bool valueDiscoverDealer = _scriptSettings.GetValue("TRAFFICKING", "DISCOVERDEALER", _settings.Trafficking.DiscoverDealer.Value);
		_scriptSettings.SetValue("TRAFFICKING", "DISCOVERDEALER", valueDiscoverDealer);
		int valueWantedLevel = _scriptSettings.GetValue("TRAFFICKING", "WANTEDLEVEL", _settings.Trafficking.WantedLevel.Value);
		_scriptSettings.SetValue("TRAFFICKING", "WANTEDLEVEL", valueWantedLevel);
	}

	private void SaveInternal()
	{
		_scriptSettings.Save();
	}
}
